services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: truckbites_mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
  
  ef-migrations:
    # db might not be ready yet, so we restart until it runs all migrations
    restart: on-failure
    build:
      context: .
      # Assuming the Dockerfile you just created is located here
      dockerfile: Eleven95.TruckBites.EF/migrations.Dockerfile
    depends_on:
      mysql:
        condition: service_started

    environment:
      - ConnectionStrings__DefaultConnection=${DB_ROOT_CONNECTION_STRING}

  phpmyadmin:
    restart: always
    image: phpmyadmin:latest
    container_name: truckbites_phpmyadmin
    depends_on:
      - mysql

    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "8081:80"
  
  customer-webapi:
    restart: always
    build:
      context: .
      dockerfile: Eleven95.TruckBites.WebApi/Dockerfile
    depends_on:
      mysql:
        condition: service_started
      ef-migrations:
        condition: service_completed_successfully

    environment:
      - JwtSettings__Authority=${CUSTOMER_WEBAPI_JWT_SETTINGS_AUTHORITY}
      - JwtSettings__Audience=${CUSTOMER_WEBAPI_JWT_SETTINGS_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${DB_APP_CONNECTION_STRING}

  customer-webapp:
    restart: always
    build:
      context: .
      dockerfile: Eleven95.TruckBites.WebApp/Eleven95.TruckBites.WebApp/Dockerfile
    depends_on:
      - mysql
      - customer-webapi

    environment:
      - Api__BaseUrl=http://customer-webapi:8080/
      - ReverseProxy__Clusters__external-api__Destinations__destination1__Address=http://customer-webapi:8080/
      - Auth0__Domain=${CUSTOMER_WEBAPP_AUTH0_DOMAIN}
      - Auth0__ClientId=${CUSTOMER_WEBAPP_AUTH0_CLIENT_ID}
      - Auth0__Audience=${CUSTOMER_WEBAPP_AUTH0_AUDIENCE}
      - Auth0__ClientSecret=${CUSTOMER_WEBAPP_AUTH0_CLIENT_SECRET}
    
    ports:
      - "8080:8080"

volumes:
  mysql_data:

