name: Deploy truckbites-customer-webapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
      # Rebuild when dependencies change
      - "Eleven95.TruckBites.Server.Shared/**"
      - "Eleven95.TruckBites.Data/**"
      - "Eleven95.TruckBites.Services/**"
      # Rebuild when the app changes
      - "Eleven95.TruckBites.WebApi/**"
      # Rebuild when the workflow changes
      - '.github/workflows/deploy-truckbites-customer-webapi.yml'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TRUCKBITESVENDORWEBAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TRUCKBITESVENDORWEBAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TRUCKBITESVENDORWEBAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Eleven95.TruckBites.WebApi/Dockerfile
          registryUrl: eleven95truckbites.azurecr.io
          registryUsername: ${{ secrets.TRUCKBITESVENDORWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TRUCKBITESVENDORWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: truckbites-customer-webapi
          resourceGroup: TruckBites
          imageToBuild: eleven95truckbites.azurecr.io/truckbites-customer-webapi:${{ github.sha }}





